language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_install:
  - composer self-update
  - composer require --prefer-dist

install:
  - kernel install --path vendor/kernel
  
script : phpunit --configuration phpunit.xml

